From python:3.8

Run pip install proselint
Run apt-get update && apt-get install -y npm && npm install -g write good

Copy entrypoint.sh /entrypoint.sh
Run chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
