name: "Lint Markdown Files"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prose-lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Run Prose Lint Action"
        uses: ./github/actions/prose-lint
        with:
          linter: "proselint" # Or set to "write-good" if you prefer
